version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.13.0

jobs:
  build-and-push-docker:
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: true
      resource_class: xlarge
    steps:
      - checkout
      - run:
          name: build Docker image
          command: docker build -t ${AWS_ECR_ACCOUNT_URL}/infra/starboard-federator:<< pipeline.git.revision >> .
      - aws-ecr/ecr-login
      - aws-ecr/push-image:
          repo: infra/starboard-federator
          tag: << pipeline.git.revision >>

workflows:
  master:
    jobs:
      - build-and-push-docker:
          context:
            - VOODOO_INFRA_TOOLS
          filters:
            branches:
              only:
                - master

