version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.13.0

jobs:
  build-and-push-docker:
    machine:
      image: ubuntu-2004:202010-01
      docker_layer_caching: true
      resource_class: xlarge
    steps:
      - aws-ecr/build-and-push-image:
          skip-when-tags-exist: true
          repo: infra/starboard-federator
          tag: << pipeline.git.revision >>
workflows:
  master:
    jobs:
      - build-and-push-docker:
          context:
            - VOODOO_INFRA_TOOLS
          filters:
            branches:
              only:
                - master

